### ISSUE TITLE
Problem when using with Travis CI

### ISSUE THREAD

**Issue by ghost** [nodkz/mongodb-memory-server#207]
I'm having issues getting the Mongo Connection String when running my tests on Travis CI (the tests work perfectly locally). Here is the relevant test code:

```js
import mongoose from 'mongoose'
import { MongoMemoryServer } from 'mongodb-memory-server'

const mongoServer = new MongoMemoryServer()

before(async () => {
  const mongoUrl = await mongoServer.getConnectionString()

  await mongoose.connect(mongoUrl, {
    useNewUrlParser: true,
    useCreateIndex: true,
    useFindAndModify: false
  })
})

after(async () => {
  await mongoose.disconnect()
  await mongoServer.stop()
})

// tests
```

I run the tests with Mocha. Here's my `.mocharc.json`:

```json
{
  "timeout": 60000,
  "require": "@babel/register",
  "exit": true,
  "spec": "src/test/**/*.test.js"
}
```

According to [this article](https://devpost.com/software/mongodb-memory-server),  `mongodb-memory-server` should just work with Travis without any `services` and `addons` in `.travis.yml`. Here's my Travis configuration:

```yml
language: node_js
node_js:
  - '10'
dist: trusty
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
  - yarn build
script:
  - yarn test
```

My Travis build breaks because it thinks the connection string is undefined. It doesn't seem to be download the MongoDB binaries. Here's the error message in the job logs:

![Screen Shot 2019-07-25 at 3 00 18 PM](https://user-images.githubusercontent.com/16217130/61842677-1d166580-aeed-11e9-88ad-50db35f3a0e0.png)

Can someone please help me with this issue?
