### ISSUE TITLE
Tip for faster travis tests?

### ISSUE THREAD

**Issue by nasht00** [nodkz/mongodb-memory-server#320]
As expected, since Travis starts fresh everytime, `npm install` downloads the binary every time. This can make the travis run a little long.

Is there any tip, a workaround to cache the binary in Travis tests?

**Comment by andreyunugro** [comment]
I encountered the same situation. 
I use [Travis's Caching Directory](https://docs.travis-ci.com/user/caching/), even though [`npm is cached by default on Travis CI`](https://docs.travis-ci.com/user/caching/#npm-cache).
For example, add this in your .travis.yml
```
cache:
  directories:
    - /home/travis/build/[org]/[project]/node_modules/.cache/mongodb-memory-server/
  npm: true
```
How to check? Run [Debug Job](https://docs.travis-ci.com/user/running-build-in-debug-mode/), and check whether mongod binary (correct version) exists before do any command.
